### ISSUE TITLE
аутентификация

### ISSUE THREAD

**Issue by kotsikavasveta** [diglabby/doika_1.2#1]

**Comment by cema93** [comment]
Я правильно понимаю, что это про баг, о том, что любой может зарегистрироваться как админ и управлять кампаниями?

**Comment by falanster** [comment]
@cema93 так я думаю гэт бэкдор. дзякуй што заўважыў, я чакаем рэвю твайго кода @fr0zen і будзем залапачываць гэту ішшу.
