### ISSUE TITLE
Тэставыя плацяжы залічваюцца ў сабраную суму, гэта збівае з толку

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika_1.2#105]
Калі ўключаны тэставыя плацяжы сабраная сума павялічваецца. Атрымліваецца, што на сайце адлюстроўваецца сабраная сума - не рэальна сабраная, а тая што прашла праз модуль. Трэба думаць над алгарытмам...

**Comment by cema93** [comment]
В версии 1,2 нет возможности в дашборде посмотреть список транзакций.
Поэтому виджет - единственный способ посмотреть проше ли тестовый платеж.
В Версии 1,3, если я правильно понимаю, будет отдельная страница, где можно будет увидеть список всех платежей, и там уже их не нужно будет учитывать в сумму собранных средств. Думаю, что это надо в бэклог doika 1.3

**Comment by lptn** [comment]
У версіі 1.3 віджэт не будзе прымаць ва увагу тэставыя плацяжы, а вось як рабіць дыферынцыяцыю тэставы/жывы ў дашбордзе - над гэтым мы яшчэ думаем тут [https://github.com/diglabby/doika/issues/335](Вырашыць, як маркіруем тэставыя дадзеныя для модуля #335)
