### ISSUE TITLE
Загрузка картинок со стороннего домена

### ISSUE THREAD

**Issue by cema93** [diglabby/doika_1.2#27]
Часть картинок для дойки грузятся с домена http://it2donate.falanster.by/
Считаю это не верным.
Необходимо проверить пути ко всем картинкам и удостовериться, что они грузятся из папки скрипта

**Comment by cema93** [comment]
Например, http://it2donate.falanster.by/client-side/assets/img/front-card.png и http://it2donate.falanster.by/client-side/assets/img/back-card.png

**Comment by falanster** [comment]
@cema93 дзякуй за код рэв'ю, гэта вельмі шаноўная функцыя у праекце. змэржыў
