### ISSUE TITLE
Still possible put decimal value in the field Required Sum (create company page)

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika_1.2#29]
На старонцы канфігурацыі падчас стварэння кампаніі ў полі "Патрэбная сума" ўсе яшчэ можна ўвесці дробную сумму. было вырашына, што модуль не працуе з дробнымі сумамі

**Comment by falanster** [comment]
@svetasemashko @cema93  адправіў на тэставанне, дзяукуй
