### ISSUE TITLE
Дата старта кампании

### ISSUE THREAD

**Issue by cema93** [diglabby/doika_1.2#39]
При создании кампании в поле "Дата пачатку" можно выбрать прошедшую дату.
Думаю, что это неправильно, хотя у других может быть иное мнение

**Comment by falanster** [comment]
@cema93 так хай пакуль будзе минулая дата. думаю тут спадзяемся на адэкватнасць супрацоўнікаў арганізацый. калі пачнуцца нейкі заўвагі з іх боку, выправім
