### ISSUE TITLE
диаграммы

### ISSUE THREAD

**Issue by kotsikavasveta** [diglabby/doika_1.2#4]
![doika_v1 2_-_ _ _](https://user-images.githubusercontent.com/35914455/36932442-f70d8796-1ed9-11e8-88be-d152717b573f.png)

[Doika v1.2 - Дыяграма кантэксту сістэмы.pdf](https://github.com/diglabby/doika_1.2/files/2034934/Doika.v1.2.-.pdf)

**Comment by Al-Shaytan-Al-Akbar** [comment]
![doika v1 2 -](https://user-images.githubusercontent.com/36993902/36949973-429b4438-2000-11e8-9492-2493e2609c88.png)

**Comment by Al-Shaytan-Al-Akbar** [comment]
![doika v1 2 -](https://user-images.githubusercontent.com/36993902/36949980-7b5ddeac-2000-11e8-9a40-b986ab24aa6b.png)

[Doika v1.2 - Схема базы дадзеных.pdf](https://github.com/diglabby/doika_1.2/files/1778883/Doika.v1.2.-.pdf)

**Comment by Al-Shaytan-Al-Akbar** [comment]
![doika v1 2 -](https://user-images.githubusercontent.com/36993902/38110221-92193ef0-33a3-11e8-87ec-044c7483e376.png)

**Comment by falanster** [comment]
@kotsikavasveta @Al-Shaytan-Al-Akbar яны зараз акрамя гэтай задачы яшчэ ёсць дзесці?
