### ISSUE TITLE
Сярэдні чэк па кампаніі

### ISSUE THREAD

**Issue by cema93** [diglabby/doika_1.2#40]
На странице "Дата пачатку" думаю, что "Сярэдні чэк па кампаніі (акцыі)" стоит округлять до 0.01 рубля, потому что это минимальная денежная единица

**Comment by falanster** [comment]
@cema93 так харошая заўвага, тут важна параметр акруглення вынесці у глабальные пераменныя або канстанты, каб усё гэта дабро можна было наладжваць у будучым. 

Прыступай)
