### ISSUE TITLE
Инсталятор приложения

### ISSUE THREAD

**Issue by pro2s** [diglabby/doika_1.2#48]
Хоть и приложение сделано для простоты установки, но все равно неподготовленному пользователю будет сложно в части развернуть дамп базы или еще в каких то моментах. 
Если приложение не ограничено по размеру, то предлагаю добавить инсталятор.
Можно использовать готовый пакет, например - https://github.com/rashidlaasri/LaravelInstaller.

P.S.: Миграции в приложении актуальны ? может добавить seeds для заполнения базы при установке приложения стандартным способом для ларавел, так как были например проблемы с развертыванием дампа на PostgreSQL.

**Comment by cema93** [comment]
Добрый день, спасибо за предложение!
Добавление инсталятора планируется в будущих релизах :)

**Comment by cema93** [comment]
Первая версия инсталятора https://github.com/cema93/doika-instalator

**Comment by cema93** [comment]
Инсталятор уже реализован. Так сказать, его первая версия.
Дальнейшая доработка инсталятора будет вестись в рамках итерации 1.3
