### ISSUE TITLE
Неправильный редирект при возвращении после оплаты

### ISSUE THREAD

**Issue by pro2s** [diglabby/doika_1.2#50]
После оплаты пользователь пренаправляется на основной сайт, вместо той странице на которой размещен модуль.

Пример, я  разместил модуль на страничке https://doika.herokuapp.com/long.html а после оплаты вернулся на главную https://doika.herokuapp.com.

**Comment by falanster** [comment]
https://trello.com/c/ibaMI5ue/

**Comment by cema93** [comment]
@fr0zen Добавь, пожалуйста, в отправляемый request информацию о текущей странице, а я на стороне бэкенда сделаю обработку данных и закроем баг :)

**Comment by falanster** [comment]
@pro2s вітаю

я правяраю, усё працуе добра.

але @cema93 тэсціць інсталяцыю з рэпа і там баг захаваўся... ці рабіў пул рэквэст гэтых зменаў?

**Comment by pro2s** [comment]
@falanster привет, вроде баг был заасайнен на @fr0zen, у меня есть наработки но я не делал pull-request

**Comment by falanster** [comment]
@pro2s рабі пул рэквэст. =) @fr0zen назірае за задачай

**Comment by falanster** [comment]
закрываем...
