### ISSUE TITLE
Сливаются цвета кнопок

### ISSUE THREAD

**Issue by cema93** [diglabby/doika_1.2#64]
Стандартный цвет кнопок с суммами сливается с цветом выбранной кнопки

**Comment by cema93** [comment]
цвета кнопок должны быть #94c840, у не выбранной кнопки должен быть стиль opacity: 0.36;

**Comment by falanster** [comment]
@cema93 пакажы на скрыншоце... як павинна быць

**Comment by cema93** [comment]
Я сеголня кипу реквест на исправление

**Comment by cema93** [comment]
Это баг текущей версии. Исправление #65
