### ISSUE TITLE
Абнавіць галоўны README.md

### ISSUE THREAD

**Issue by lptn** [diglabby/doika_1.2#68]
Спадарства, зайшоў я на праект каб можа з чым дапамагчы але так і не зразумеў што гэта за модуль і як яно будзе працаваць і вяглядаць у рэшце рэшт

Таму хачу параіць канкрэтныя крокі:
 1. Дадаць выяву як модуль выглядае
 1. Дадаць простую схему каб карыстальнік мог зразумець як гэта працуе
 1. Вынесці інфармацыю для распрацоўшчыкаў у асобны дакумэнт (і пералінкаваць)

**Comment by lptn** [comment]
@falanster 
>Збіраемся яе у бліжйэшы час склейваць.

Добра, я дачакаюся кали змержаце і вярнуся да гэтага пытання

Дзякуй за вокгук!

**Comment by cema93** [comment]
@lptn Доброй ночи, смержили :)

**Comment by lptn** [comment]
Крута, калі тут заўтра хто будзе https://www.facebook.com/events/230970547578868/ ці тут https://css-minsk-js.by/ пазаўтра -- мажам абмеркаваць праект  ;)

**Comment by falanster** [comment]
@lptn мы зараз як раз працуем з вікі.
Мо прапануеце сваю струткуру? 

https://github.com/diglabby/doika_1.2/wiki
у тым ліку на наступнай ітэрацыі 
https://github.com/diglabby/doika/wiki

**Comment by lptn** [comment]
@falanster 
Дзякуй што спыталі


Я пакуль модуль не глядзеў,адпаведна сам ня ведаею як ён працуе, таму падбрабязна распісаць не атрымаецца (ждя гэтага патрэбна хаця б раз усталяваць яго).

З дакументацыя трэба ка было ясна як:
 - модуль выглядае (я ужо дадаў ў PR #85)
 - як плаціць праз модуль (зрабіць аніміраваны gif + спасылкі на 1-2 старонкі дзе модуль ужо стаіць)
 - як усталяваць модуль
   - юрыдычныя патрабаванні
   - тэхнічныя патрабаванні
   -  спрошчаная схема працы модуля (лепей выявай)
 - кагфігурацыя модуля
 - як абнашляць модуль

**Comment by falanster** [comment]
@lptn ага, дзякуй.

рэквест разглядаем

усё версіі з 1.3 будуць ляжаць на ўніверсальнай назве https://github.com/diglabby/doika/
