### ISSUE TITLE
Праблема вываду. З'явіўся непрадбачаны вывад на кампе Крылаў

### ISSUE THREAD

**Issue by falanster** [diglabby/doika_1.2#76]
![kryly-bug](https://user-images.githubusercontent.com/1325280/45798430-8bc5d980-bcb2-11e8-84e3-12ec7625c7a4.JPG)
галоўная старонка wingsangels.by

**Comment by cema93** [comment]
Для проверки необходимо знать ОС, браузер и его версию

**Comment by cema93** [comment]
но, скорее всего, проблема изза кривой установки.

**Comment by falanster** [comment]
задачу закрываю усё там працуе ўжо
