### ISSUE TITLE
UX праблемы і прапановы

### ISSUE THREAD

**Issue by lptn** [diglabby/doika_1.2#81]
Пакуль вока не замылілася, зарэпорчу свае думкі наконт UX

![image](https://user-images.githubusercontent.com/5278175/45932781-58bd6780-bf8a-11e8-91cd-11432a51f998.png)

Адразу скажу, што я не дызайнер, пішу з кропкі гледжання карыстальніка

## Праблемы

 1.  Усе кантролы выглядаюць аднолькава (усе 3 тыпа: input[type="text"], radio/button, button[type="submit"])
 1. Форму немагчыма засабміціць выкарыстоўваючы Enter
 1. Слова "Модуль" стварае хоць і мінімальную, але непатрэную кагнетыўную назрузку, яго можна проста выдаліць, а ў якасці мікра-рэкралы лепей дадаць пасылку на гэты рэпазыторый

Вось так на маю думку выглядае добрая форма данату
![image](https://user-images.githubusercontent.com/5278175/45932933-ef8b2380-bf8c-11e8-8ee0-4baec090c9e6.png)

PS: Ці можна страваць issues па-ангельску?

**Comment by falanster** [comment]
@lptn вітаю,

1. Юзэр досвед. @nastyafrosty @svetit можа вам каментары будуць карысны. гляньце. патэнцыйна усё можна мяняць
2. Мовы. Мы абмяркоўвалі, гэта пытанне на сустрэчах. З большага можна на любой мове. Тут пытанне для каго задача пішацца. Пакуль праект сфакусаваны на Беларусь, таму мы па-беларуску і па-руску вядзем.

**Comment by falanster** [comment]
@lptn дарэчы гэту штуку можна рэалізаваць. "Форму немагчыма засабміціць выкарыстоўваючы Enter"

**Comment by falanster** [comment]
@Tyuba4 глядзі твае думкі тут паўтараюцца.


@lptn 
Можна заўтра ў абед завяхацца або ў сераду вечарам 19:30 для першай сувязі прапаную тут: https://appear.in/falanster

**Comment by lptn** [comment]
Зыкрываю, усе апісаныя прапановы разбярэм паступова ;)
