### ISSUE TITLE
У поле шорткод трэба дадаць адрас /doika-loader.js 

### ISSUE THREAD

**Issue by svetasemashko** [diglabby/doika_1.2#88]
Скрыпт для адлюстравання модуля трэба шукаць у гайдзе і капіраваць. Шорткод трэба шукаць на старонке стварэння кампаніі і капіраваць. Было б зручней генерыраваць script div у адным месцы адначасова.

**Comment by fr0zen** [comment]
@cema93 Зрабіў патрэбныя праўкі, зачыняю
