### ISSUE TITLE
Перакласці інсталятар на бел мову і давесці 

### ISSUE THREAD

**Issue by falanster** [diglabby/doika_1.2#89]
Заўвагі @cema93 

1. праверка хэша ларавэль (задача з зорачкай)
2. адпраўляць на https://doika.falanster.by (https) 
3. падпісаць крокі і наспісаць невялікія каментарs на кожнай старонцы з @svetasemashko 
4. прадумаць юікс інсталятара з @nastyafrosty

**Comment by cema93** [comment]
@svetasemashko @nastyafrosty
Ввиду большого количества изменений, которые сейчас вношу в инсталятор, разработку веду в отдельном репозитории https://github.com/cema93/doika-instalator

**Comment by cema93** [comment]
1.  при текущей реализации бесполезно проверять хэш
2. Исправлено
3. сделано в #99

**Comment by cema93** [comment]
В 1.2 инсталятор больше дорабатываться не будет.
Дальнейшая доработка будет в 1.3
